# Fraunhofer CPG Test Dataset: JSONL -> CSV + CWE Groups

Ноутбук читает `datasets/tasks 3.jsonl`, разворачивает JSONL в `pandas.DataFrame`, сохраняет CSV и формирует группы CWE. Первая рабочая группа: `taint_flow_vuln`.

In [2]:
from pathlib import Path
import json

try:
    import pandas as pd
except ModuleNotFoundError as exc:
    raise ModuleNotFoundError("Install pandas before running this notebook: python3 -m pip install pandas") from exc

pd.set_option("display.max_columns", 80)
pd.set_option("display.max_colwidth", 180)

DATASET_PATH = Path("/Users/nident/Desktop/JOB/ScolTech/FraunhoferCPG_test/datasets/tasks 3.jsonl")
OUTPUT_CSV_PATH = DATASET_PATH.with_suffix(".csv")

DATASET_PATH, OUTPUT_CSV_PATH

(PosixPath('/Users/nident/Desktop/JOB/ScolTech/FraunhoferCPG_test/datasets/tasks 3.jsonl'),
 PosixPath('/Users/nident/Desktop/JOB/ScolTech/FraunhoferCPG_test/datasets/tasks 3.csv'))

## Read JSONL

Каждая строка JSONL содержит верхнеуровневые блоки `vuln`, `task` и `selected`.

In [3]:
def read_jsonl(path: Path) -> list[dict]:
    records = []
    with path.open("r", encoding="utf-8") as fh:
        for line_no, line in enumerate(fh, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSON at line {line_no}: {exc}") from exc
    return records


records = read_jsonl(DATASET_PATH)
len(records)

968

In [4]:
records[0].keys(), records[0]["vuln"].keys(), records[0]["task"].keys()

(dict_keys(['vuln', 'task', 'selected']),
 dict_keys(['id', 'project', 'cve_ids', 'details', 'summary', 'cwe_ids', 'vuln_commit', 'safe_commit', 'snippets', 'contexts']),
 dict_keys(['id', 'similarity', 'confidence', 'reasoning', 'project', 'safe_commit', 'vuln_commit', 'last_commit']))

## Transform To DataFrame

`pd.json_normalize` разворачивает вложенные словари в колонки вида `vuln.id`, `task.project`. Списки и сложные объекты оставляем в отдельных колонках, а для CSV сериализуем их обратно в JSON-строки.

In [5]:
df = pd.json_normalize(records, sep=".")

df["vuln.cwe_ids"] = df["vuln.cwe_ids"].apply(lambda value: value if isinstance(value, list) else [])
df["vuln.cwe_ids_text"] = df["vuln.cwe_ids"].apply(lambda values: ",".join(values))
df["vuln.cwe_count"] = df["vuln.cwe_ids"].apply(len)
df["vuln.cve_ids_text"] = df["vuln.cve_ids"].apply(lambda values: ",".join(values) if isinstance(values, list) else "")
df["vuln.snippet_count"] = df["vuln.snippets"].apply(lambda values: len(values) if isinstance(values, list) else 0)
df["vuln.context_count"] = df["vuln.contexts"].apply(lambda values: len(values) if isinstance(values, list) else 0)

df.shape

(968, 24)

In [6]:
df.head(3)

,selected,vuln.id,vuln.project,vuln.cve_ids,vuln.details,vuln.summary,vuln.cwe_ids,vuln.vuln_commit,vuln.safe_commit,vuln.snippets,vuln.contexts,task.id,task.similarity,task.confidence,task.reasoning,task.project,task.safe_commit,task.vuln_commit,task.last_commit,vuln.cwe_ids_text,vuln.cwe_count,vuln.cve_ids_text,vuln.snippet_count,vuln.context_count
0,False,GHSA-h7qf-qmf3-85qg,allure-framework/allure2,[CVE-2025-52888],### Summary\nA critical XML External Entity (XXE) vulnerability exists in the xunit-xml-plugin used by Allure 2. The plugin fails to securely configure the XML parser (`Documen...,Allure Report allows Improper XXE Restriction via DocumentBuilderFactory,[CWE-611],eaa87ff7d93e79074f7a1d785740bd3fed2f89fd,cbcb33719851ff70adce85d38e15d20fc58d4eb7,"[{'vuln_snippet': 'public class JunitXmlPlugin { private void parseRootElement(final Path resultsDirectory, final Path parsedFile, final ...","[{'vuln_context': '/** * Plugin that reads data in JUnit.xml format. * * @since 2.0 */ @SuppressWarnings({""PMD.ExcessiveImports"", ""ClassDataAbstractionCoupling"", ""ClassFanO...",GHSA-8c3x-hq82-gjcm,0.91,0.95,Both vulnerabilities involve improper configuration of DocumentBuilderFactory leading to XXE (CWE-611). Identical root cause: DTD and external entity processing not disabled. S...,HL7/fhir-ig-publisher,3560de2f486d688a3ddcf4aa54d8bdacea380c3d,ba0b48d4ddb4dbffb45e0d45c43069e99a038385,ff300219c66c19d76fb5e08c92a4d487b71cf15c,CWE-611,1,CVE-2025-52888,2,2
1,True,GHSA-h7qf-qmf3-85qg,allure-framework/allure2,[CVE-2025-52888],### Summary\nA critical XML External Entity (XXE) vulnerability exists in the xunit-xml-plugin used by Allure 2. The plugin fails to securely configure the XML parser (`Documen...,Allure Report allows Improper XXE Restriction via DocumentBuilderFactory,[CWE-611],eaa87ff7d93e79074f7a1d785740bd3fed2f89fd,cbcb33719851ff70adce85d38e15d20fc58d4eb7,"[{'vuln_snippet': 'public class JunitXmlPlugin { private void parseRootElement(final Path resultsDirectory, final Path parsedFile, final ...","[{'vuln_context': '/** * Plugin that reads data in JUnit.xml format. * * @since 2.0 */ @SuppressWarnings({""PMD.ExcessiveImports"", ""ClassDataAbstractionCoupling"", ""ClassFanO...",GHSA-2466-4485-4pxj,0.85,0.95,Both vulnerabilities are XXE issues (CWE-611) caused by improper XML parser configuration allowing external entity resolution. Attack vectors differ slightly: one exploits HTTP...,Robothy/local-s3,d6ed756ceb30c1eb9d4263321ac683d734f8836f,009901882be8b543e85b67c5ec2e9f30d83d62ef,0244e9bbb5b1a9b6f8fa3f9c19fc9a9243f4fc97,CWE-611,1,CVE-2025-52888,2,2
2,True,GHSA-h7qf-qmf3-85qg,allure-framework/allure2,[CVE-2025-52888],### Summary\nA critical XML External Entity (XXE) vulnerability exists in the xunit-xml-plugin used by Allure 2. The plugin fails to securely configure the XML parser (`Documen...,Allure Report allows Improper XXE Restriction via DocumentBuilderFactory,[CWE-611],eaa87ff7d93e79074f7a1d785740bd3fed2f89fd,cbcb33719851ff70adce85d38e15d20fc58d4eb7,"[{'vuln_snippet': 'public class JunitXmlPlugin { private void parseRootElement(final Path resultsDirectory, final Path parsedFile, final ...","[{'vuln_context': '/** * Plugin that reads data in JUnit.xml format. * * @since 2.0 */ @SuppressWarnings({""PMD.ExcessiveImports"", ""ClassDataAbstractionCoupling"", ""ClassFanO...",GHSA-47qw-ccjm-9c2c,0.85,0.95,Both vulnerabilities are XXE issues (CWE-611) caused by improper XML parser configuration allowing external entity expansion. Attack vectors differ slightly: one exploits multi...,Robothy/local-s3,d6ed756ceb30c1eb9d4263321ac683d734f8836f,009901882be8b543e85b67c5ec2e9f30d83d62ef,0244e9bbb5b1a9b6f8fa3f9c19fc9a9243f4fc97,CWE-611,1,CVE-2025-52888,2,2

## Save CSV

In [7]:
def to_csv_safe(value):
    if isinstance(value, (list, dict)):
        return json.dumps(value, ensure_ascii=False)
    return value


if hasattr(df, "map"):
    df_csv = df.map(to_csv_safe)
else:
    df_csv = df.applymap(to_csv_safe)
df_csv.to_csv(OUTPUT_CSV_PATH, index=False)

OUTPUT_CSV_PATH

PosixPath('/Users/nident/Desktop/JOB/ScolTech/FraunhoferCPG_test/datasets/tasks 3.csv')

## CWE Groups

Группы заданы как массивы CWE. Сейчас основная рабочая группа - `taint_flow_vuln`; остальные группы оставлены как расширяемая разметка для следующих итераций.

In [8]:
CWE_GROUPS = {
    # Untrusted input reaches a security-sensitive sink: injection, traversal, parser abuse, SSRF, unsafe deserialization, upload, etc.
    "taint_flow_vuln": [
        "CWE-20",   # Improper Input Validation
        "CWE-22",   # Path Traversal
        "CWE-36",   # Absolute Path Traversal
        "CWE-79",   # Cross-Site Scripting
        "CWE-80",   # XSS - Basic
        "CWE-81",   # XSS - Error Message
        "CWE-90",   # LDAP Injection
        "CWE-91",   # XML Injection
        "CWE-94",   # Code Injection
        "CWE-95",   # Eval Injection
        "CWE-150",  # Improper Neutralization of Escape/Meta/Control Sequences
        "CWE-434",  # Unrestricted Upload
        "CWE-502",  # Deserialization of Untrusted Data
        "CWE-611",  # XXE
        "CWE-915",  # Improperly Controlled Modification of Object Attributes
        "CWE-918",  # SSRF
    ],
    "authorization_missing_security_guard": ["CWE-285", "CWE-862", "CWE-863"],
    "state_machine_business_logic": ["CWE-348", "CWE-352"],
    "race_condition_atomicity": [],
    "authentication_session_lifecycle": ["CWE-287", "CWE-289", "CWE-522", "CWE-523"],
    "exceptional_paths_fail_open": ["CWE-754", "CWE-755"],
    "crypto_security_api_misuse": [
        "CWE-295", 
        "CWE-297",
        "CWE-611"
    ],
    "sensitive_data_exposure": ["CWE-200", "CWE-209", "CWE-532", "CWE-922"],
    "memory_resource_lifetime": ["CWE-400", "CWE-770", "CWE-789"],
    "configuration_dependency_security": [],
}

taint_flow_vuln = CWE_GROUPS["taint_flow_vuln"]
taint_flow_vuln

['CWE-20',
 'CWE-22',
 'CWE-36',
 'CWE-79',
 'CWE-80',
 'CWE-81',
 'CWE-90',
 'CWE-91',
 'CWE-94',
 'CWE-95',
 'CWE-150',
 'CWE-434',
 'CWE-502',
 'CWE-611',
 'CWE-915',
 'CWE-918']

In [9]:
def has_any_cwe(cwe_ids: list[str], group: list[str]) -> bool:
    return bool(set(cwe_ids) & set(group))


for group_name, group_cwes in CWE_GROUPS.items():
    df[group_name] = df["vuln.cwe_ids"].apply(lambda cwes, group_cwes=group_cwes: has_any_cwe(cwes, group_cwes))

taint_flow_df = df[df["taint_flow_vuln"]].copy()
taint_flow_records = taint_flow_df.to_dict("records")

taint_flow_df.shape, len(taint_flow_records)

((694, 34), 694)

## Quick Checks

In [10]:
cwe_counts = (
    df.explode("vuln.cwe_ids")
      .groupby("vuln.cwe_ids", dropna=False)
      .size()
      .sort_values(ascending=False)
      .rename("count")
      .reset_index()
)

cwe_counts.head(40)

   vuln.cwe_ids  count
0        CWE-79    232
1        CWE-22    174
2       CWE-611    108
3        CWE-20    106
4       CWE-862     89
5       CWE-502     81
6       CWE-400     61
7       CWE-770     58
8        CWE-94     47
9       CWE-532     39
10      CWE-200     31
11      CWE-295     24
12      CWE-863     20
13      CWE-918     18
14       CWE-36     18
15      CWE-434     11
16      CWE-285     11
17      CWE-297     11
18       CWE-80      9
19       CWE-81      9
20      CWE-915      9
21      CWE-150      9
22      CWE-523      9
23      CWE-754      9
24      CWE-352      9
25      CWE-348      9
26      CWE-287      9
27       CWE-27      9
28      CWE-755      8
29      CWE-789      8
30       CWE-91      7
31       CWE-95      6
32      CWE-522      4
33      CWE-922      4
34      CWE-209      3
35       CWE-90      2
36      CWE-289      1

In [11]:
group_counts = (
    pd.Series({group_name: int(df[group_name].sum()) for group_name in CWE_GROUPS})
      .sort_values(ascending=False)
      .rename("rows")
      .reset_index()
      .rename(columns={"index": "group"})
)

group_counts

                                  group  rows
0                       taint_flow_vuln   694
1              memory_resource_lifetime   119
2  authorization_missing_security_guard   111
3               sensitive_data_exposure    61
4            crypto_security_api_misuse    24
5      authentication_session_lifecycle    23
6          state_machine_business_logic    18
7           exceptional_paths_fail_open    17
8              race_condition_atomicity     0
9     configuration_dependency_security     0

In [12]:
taint_flow_df[[
    "vuln.id",
    "vuln.project",
    "vuln.summary",
    "vuln.cwe_ids_text",
    "task.id",
    "task.project",
    "selected",
]].head(20)

,vuln.id,vuln.project,vuln.summary,vuln.cwe_ids_text,task.id,task.project,selected
0,GHSA-h7qf-qmf3-85qg,allure-framework/allure2,Allure Report allows Improper XXE Restriction via DocumentBuilderFactory,CWE-611,GHSA-8c3x-hq82-gjcm,HL7/fhir-ig-publisher,False
1,GHSA-h7qf-qmf3-85qg,allure-framework/allure2,Allure Report allows Improper XXE Restriction via DocumentBuilderFactory,CWE-611,GHSA-2466-4485-4pxj,Robothy/local-s3,True
2,GHSA-h7qf-qmf3-85qg,allure-framework/allure2,Allure Report allows Improper XXE Restriction via DocumentBuilderFactory,CWE-611,GHSA-47qw-ccjm-9c2c,Robothy/local-s3,True
3,GHSA-h7qf-qmf3-85qg,allure-framework/allure2,Allure Report allows Improper XXE Restriction via DocumentBuilderFactory,CWE-611,GHSA-5gwh-r76w-934h,jenkinsci/qualys-was-plugin,False
4,GHSA-h7qf-qmf3-85qg,allure-framework/allure2,Allure Report allows Improper XXE Restriction via DocumentBuilderFactory,CWE-611,GHSA-68j8-fp38-p48q,gematik/app-referencevalidator,True
5,GHSA-h7qf-qmf3-85qg,allure-framework/allure2,Allure Report allows Improper XXE Restriction via DocumentBuilderFactory,CWE-611,GHSA-6fhj-vr9j-g45r,CycloneDX/cyclonedx-core-java,False
6,GHSA-h7qf-qmf3-85qg,allure-framework/allure2,Allure Report allows Improper XXE Restriction via DocumentBuilderFactory,CWE-611,GHSA-7jc7-g598-2p64,opensagres/xdocreport,True
7,GHSA-h7qf-qmf3-85qg,allure-framework/allure2,Allure Report allows Improper XXE Restriction via DocumentBuilderFactory,CWE-611,GHSA-fvfq-q238-j7j3,wso2/carbon-mediation,False
8,GHSA-h7qf-qmf3-85qg,allure-framework/allure2,Allure Report allows Improper XXE Restriction via DocumentBuilderFactory,CWE-611,GHSA-g6wm-2v64-wq36,Robothy/local-s3,False
27,GHSA-h856-ffvv-xvr4,jenkinsci/remoting,Jenkins Remoting library arbitrary file read vulnerability,"CWE-22,CWE-754",GHSA-478x-m3mx-7j3f,jenkinsci/htmlpublisher-plugin,True
28,GHSA-h856-ffvv-xvr4,jenkinsci/remoting,Jenkins Remoting library arbitrary file read vulnerability,"CWE-22,CWE-754",GHSA-5mp4-32rr-v3x5,treasure-data/digdag,False
29,GHSA-h856-ffvv-xvr4,jenkinsci/remoting,Jenkins Remoting library arbitrary file read vulnerability,"CWE-22,CWE-754",GHSA-6f9g-cxwr-q5jr,jenkinsci/jenkins,False
30,GHSA-h856-ffvv-xvr4,jenkinsci/remoting,Jenkins Remoting library arbitrary file read vulnerability,"CWE-22,CWE-754",GHSA-cg24-jjr5-rxmf,Devan-Kerman/ARRP,False
31,GHSA-h856-ffvv-xvr4,jenkinsci/remoting,Jenkins Remoting library arbitrary file read vulnerability,"CWE-22,CWE-754",GHSA-g64r-xf39-q4p5,apache/zeppelin,False
32,GHSA-h856-ffvv-xvr4,jenkinsci/remoting,Jenkins Remoting library arbitrary file read vulnerability,"CWE-22,CWE-754",GHSA-j273-m5qq-6825,junrar/junrar,True
33,GHSA-h856-ffvv-xvr4,jenkinsci/remoting,Jenkins Remoting library arbitrary file read vulnerability,"CWE-22,CWE-754",GHSA-qfwq-6jh6-8xx4,OpenRefine/OpenRefine,False
34,GHSA-h856-ffvv-xvr4,jenkinsci/remoting,Jenkins Remoting library arbitrary file read vulnerability,"CWE-22,CWE-754",GHSA-wpcv-5jgp-69f3,Netflix/genie,False
35,GHSA-h856-ffvv-xvr4,jenkinsci/remoting,Jenkins Remoting library arbitrary file read vulnerability,"CWE-22,CWE-754",GHSA-3p8v-w8mr-m3x8,OpenRefine/simile-butterfly,False
36,GHSA-7w75-32cg-r6g2,apache/tomcat,Apache Tomcat Denial of Service due to improper input validation vulnerability for HTTP/2 requests,CWE-20,GHSA-qq5r-98hh-rxc9,apache/tomcat,False
37,GHSA-7w75-32cg-r6g2,apache/tomcat,Apache Tomcat Denial of Service due to improper input validation vulnerability for HTTP/2 requests,CWE-20,GHSA-6h4f-pj3g-q8fq,undertow-io/undertow,True

In [13]:
import os
projects = os.listdir("/Users/nident/Desktop/JOB/ScolTech/CPG_analysis/data/sweep")
projects = [project.replace("__", '/') for project in projects]
projects

['FasterXML/jackson-core',
 'jenkinsci/gatling-plugin',
 'jenkinsci/structs-plugin',
 'jenkinsci/delphix-plugin',
 'allure-framework/allure2',
 'jenkinsci/htmlpublisher-plugin',
 'gematik/app-referencevalidator',
 'apache/jspwiki',
 'x-stream/xstream',
 'CycloneDX/cyclonedx-core-java',
 'outputs',
 'gaul/s3proxy']

In [14]:
mask = taint_flow_df["vuln.project"].isin(projects)
matched = taint_flow_df[mask]

matched.to_csv("/Users/nident/Desktop/JOB/ScolTech/FraunhoferCPG_test/datasets/matched_taint_flow_vuln.csv", index=False)

In [19]:
pd.set_option("display.max_rows", 1000)
matched

,selected,vuln.id,vuln.project,vuln.cve_ids,vuln.details,vuln.summary,vuln.cwe_ids,vuln.vuln_commit,vuln.safe_commit,vuln.snippets,vuln.contexts,task.id,task.similarity,task.confidence,task.reasoning,task.project,task.safe_commit,task.vuln_commit,task.last_commit,vuln.cwe_ids_text,vuln.cwe_count,vuln.cve_ids_text,vuln.snippet_count,vuln.context_count,taint_flow_vuln,authorization_missing_security_guard,state_machine_business_logic,race_condition_atomicity,authentication_session_lifecycle,exceptional_paths_fail_open,crypto_security_api_misuse,sensitive_data_exposure,memory_resource_lifetime,configuration_dependency_security
0,False,GHSA-h7qf-qmf3-85qg,allure-framework/allure2,[CVE-2025-52888],### Summary\nA critical XML External Entity (XXE) vulnerability exists in the xunit-xml-plugin used by Allure 2. The plugin fails to securely configure the XML parser (`Documen...,Allure Report allows Improper XXE Restriction via DocumentBuilderFactory,[CWE-611],eaa87ff7d93e79074f7a1d785740bd3fed2f89fd,cbcb33719851ff70adce85d38e15d20fc58d4eb7,"[{'vuln_snippet': 'public class JunitXmlPlugin { private void parseRootElement(final Path resultsDirectory, final Path parsedFile, final ...","[{'vuln_context': '/** * Plugin that reads data in JUnit.xml format. * * @since 2.0 */ @SuppressWarnings({""PMD.ExcessiveImports"", ""ClassDataAbstractionCoupling"", ""ClassFanO...",GHSA-8c3x-hq82-gjcm,0.91,0.95,Both vulnerabilities involve improper configuration of DocumentBuilderFactory leading to XXE (CWE-611). Identical root cause: DTD and external entity processing not disabled. S...,HL7/fhir-ig-publisher,3560de2f486d688a3ddcf4aa54d8bdacea380c3d,ba0b48d4ddb4dbffb45e0d45c43069e99a038385,ff300219c66c19d76fb5e08c92a4d487b71cf15c,CWE-611,1,CVE-2025-52888,2,2,True,False,False,False,False,False,False,False,False,False
1,True,GHSA-h7qf-qmf3-85qg,allure-framework/allure2,[CVE-2025-52888],### Summary\nA critical XML External Entity (XXE) vulnerability exists in the xunit-xml-plugin used by Allure 2. The plugin fails to securely configure the XML parser (`Documen...,Allure Report allows Improper XXE Restriction via DocumentBuilderFactory,[CWE-611],eaa87ff7d93e79074f7a1d785740bd3fed2f89fd,cbcb33719851ff70adce85d38e15d20fc58d4eb7,"[{'vuln_snippet': 'public class JunitXmlPlugin { private void parseRootElement(final Path resultsDirectory, final Path parsedFile, final ...","[{'vuln_context': '/** * Plugin that reads data in JUnit.xml format. * * @since 2.0 */ @SuppressWarnings({""PMD.ExcessiveImports"", ""ClassDataAbstractionCoupling"", ""ClassFanO...",GHSA-2466-4485-4pxj,0.85,0.95,Both vulnerabilities are XXE issues (CWE-611) caused by improper XML parser configuration allowing external entity resolution. Attack vectors differ slightly: one exploits HTTP...,Robothy/local-s3,d6ed756ceb30c1eb9d4263321ac683d734f8836f,009901882be8b543e85b67c5ec2e9f30d83d62ef,0244e9bbb5b1a9b6f8fa3f9c19fc9a9243f4fc97,CWE-611,1,CVE-2025-52888,2,2,True,False,False,False,False,False,False,False,False,False
2,True,GHSA-h7qf-qmf3-85qg,allure-framework/allure2,[CVE-2025-52888],### Summary\nA critical XML External Entity (XXE) vulnerability exists in the xunit-xml-plugin used by Allure 2. The plugin fails to securely configure the XML parser (`Documen...,Allure Report allows Improper XXE Restriction via DocumentBuilderFactory,[CWE-611],eaa87ff7d93e79074f7a1d785740bd3fed2f89fd,cbcb33719851ff70adce85d38e15d20fc58d4eb7,"[{'vuln_snippet': 'public class JunitXmlPlugin { private void parseRootElement(final Path resultsDirectory, final Path parsedFile, final ...","[{'vuln_context': '/** * Plugin that reads data in JUnit.xml format. * * @since 2.0 */ @SuppressWarnings({""PMD.ExcessiveImports"", ""ClassDataAbstractionCoupling"", ""ClassFanO...",GHSA-47qw-ccjm-9c2c,0.85,0.95,Both vulnerabilities are XXE issues (CWE-611) caused by improper XML parser configuration allowing external entity expansion. Attack vectors differ slightly: one exploits multi...,Robothy/local-s3,d6ed756ceb30c1eb9d4263321ac683d734f8836f,009901882be8b543e85b67c5ec2e9f30d83d62ef,0244e9bbb5b1a9b6f8fa3f9c19fc9a9243f4fc97,CWE-611,1,CVE-2025-52888,2,2,True,False,False,False,False,False,False,False,False,False
3,False,GHSA-h7qf-qmf3-85qg,allure-framework/allure2,[CVE-2025-52888],### Summary\nA critical XML External Entity (XXE) vulnerability exists in the xunit-xml-plugin used by Allure 2. The plugin fails to securely configure the XML parser (`Documen...,Allure Report allows Improper XXE Restriction via DocumentBuilderFactory,[CWE-611],eaa87ff7d93e79074f7a1d785740bd3fed2f89fd,cbcb33719851ff70adce85d38e15d20fc58d4eb7,"[{'vuln_snippet': 'public class JunitXmlPlugin { private void parseRootElement(final Path resultsDirectory, final Path parsedFile, final ...","[{'vuln_context': '/** * Plugin that reads data in JUnit.xml format. * * @since 2.0 */ @SuppressWarnings({""PMD.ExcessiveImports"", ""ClassDataAbstractionCoupling"", ""ClassFanO...",GHSA-5gwh-r76w-934h,0.85,0.95,Both vulnerabilities are XXE issues (CWE-611) due to improper restriction of XML external entities. Root cause is identical: unsafe XML parsing without disabling external entit...,jenkinsci/qualys-was-plugin,b4eeb34747fa1b934abbdf686102f6495fdb02ee,7bc24a7ad95c71e0d4240f80fea7c852c16d143b,a3cd163b1da365e012c5165e1c8e15189b485a2e,CWE-611,1,CVE-2025-52888,2,2,True,False,False,False,False,False,False,False,False,False
4,True,GHSA-h7qf-qmf3-85qg,allure-framework/allure2,[CVE-2025-52888],### Summary\nA critical XML External Entity (XXE) vulnerability exists in the xunit-xml-plugin used by Allure 2. The plugin fails to securely configure the XML parser (`Documen...,Allure Report allows Improper XXE Restriction via DocumentBuilderFactory,[CWE-611],eaa87ff7d93e79074f7a1d785740bd3fed2f89fd,cbcb33719851ff70adce85d38e15d20fc58d4eb7,"[{'vuln_snippet': 'public class JunitXmlPlugin { private void parseRootElement(final Path resultsDirectory, final Path parsedFile, final ...","[{'vuln_context': '/** * Plugin that reads data in JUnit.xml format. * * @since 2.0 */ @SuppressWarnings({""PMD.ExcessiveImports"", ""ClassDataAbstractionCoupling"", ""ClassFanO...",GHSA-68j8-fp38-p48q,0.85,0.95,"Both vulnerabilities are XXE issues (CWE-611) caused by improper XML parser configuration, leading to SSRF. Different parsers used (Woodstox vs DocumentBuilderFactory), but sam...",gematik/app-referencevalidator,d6d27613fab7a8dd08534946f29e0c51f319cad6,d276b02be9c836b3ccc6979df799e7dca06474ac,f1b1f7c8be9f9ae2f4fa452982435f699bc77a2c,CWE-611,1,CVE-2025-52888,2,2,True,False,False,False,False,False,False,False,False,False
5,False,GHSA-h7qf-qmf3-85qg,allure-framework/allure2,[CVE-2025-52888],### Summary\nA critical XML External Entity (XXE) vulnerability exists in the xunit-xml-plugin used by Allure 2. The plugin fails to securely configure the XML parser (`Documen...,Allure Report allows Improper XXE Restriction via DocumentBuilderFactory,[CWE-611],eaa87ff7d93e79074f7a1d785740bd3fed2f89fd,cbcb33719851ff70adce85d38e15d20fc58d4eb7,"[{'vuln_snippet': 'public class JunitXmlPlugin { private void parseRootElement(final Path resultsDirectory, final Path parsedFile, final ...","[{'vuln_context': '/** * Plugin that reads data in JUnit.xml format. * * @since 2.0 */ @SuppressWarnings({""PMD.ExcessiveImports"", ""ClassDataAbstractionCoupling"", ""ClassFanO...",GHSA-6fhj-vr9j-g45r,0.85,0.95,Both vulnerabilities are CWE-611 (XXE) with identical root causes: insecure XML parser configuration allowing external entity expansion. Attack vectors differ slightly (BOM val...,CycloneDX/cyclonedx-core-java,af0ec75c93c03f93733a070c5132554490af5314,7c7294b3d112ba423c94b1f42994e6fb00fb241e,681ed28386b2135c5ff4ed9a3c895fa9c4900289,CWE-611,1,CVE-2025-52888,2,2,True,False,False,False,False,False,False,False,False,False
6,True,GHSA-h7qf-qmf3-85qg,allure-framework/allure2,[CVE-2025-52888],### Summary\nA critical XML External Entity (XXE) vulnerability exists in the xunit-xml-plugin used by Allure 2. The plugin fails to securely configure the XML parser (`Documen...,Allure Report allows Improper XXE Restriction via DocumentBuilderFactory,[CWE-611],eaa87ff7d93e79074f7a1d785740bd3fed2f89fd,cbcb33719851ff70adce85d38e15d20fc58d4eb7,"[{'vuln_snippet': 'public class JunitXmlPlugin { private void parseRootElement(final Path resultsDirectory, final Path parsedFile, final ...","[{'vuln_context': '/** * Plugin that reads data in JUnit.xml format. * * @since 2.0 */ @SuppressWarnings({""PMD.ExcessiveImports"", ""ClassDataAbstractionCoupling"", ""ClassFanO...",GHSA-7jc7-g598-2p64,0.85,0.95,Both vulnerabilities are XXE issues (CWE-611) caused by improper XML parser configuration. They share the same root cause: unsafe initialization of XML parsers without disablin...,opensagres/xdocreport,d9b90ae6c9489dc43f6427ec7b315cab34125332,2ee44f5f66c7ab31cc64635d8723d34fb861eec9,e7a7431a880d0a2217f9c3af709a13011844a92a,CWE-611,1,CVE-2025-52888,2,2,True,False,False,False,False,False,False,False,False,False
7,False,GHSA-h7qf-qmf3-85qg,allure-framework/allure2,[CVE-2025-52888],### Summary\nA critical XML External Entity (XXE) vulnerability exists in the xunit-xml-plugin used by Allure 2. The plugin fails to securely configure the XML parser (`Documen...,Allure Report allows Improper XXE Restriction via DocumentBuilderFactory,[CWE-611],eaa87ff7d93e79074f7a1d785740bd3fed2f89fd,cbcb33719851ff70adce85d38e15d20fc58d4eb7,"[{'vuln_snippet': 'public class JunitXmlPlugin { private void parseRootElement(final Path resultsDirectory, final Path parsedFile, final ...","[{'vuln_context': '/** * Plugin that reads data in JUnit.xml format. * * @since 2.0 */ @SuppressWarnings({""PMD.ExcessiveImports"", ""ClassDataAbstractionCoupling"", ""ClassFanO...",GHSA-fvfq-q238-j7j3,0.85,0.95,Both vulnerabilities are XXE issues (CWE-611) caused by improper XML parser configuration. They share the same root cause: failure to restrict external entity resolution. Attac...,wso2/carbon-mediation,b995b2f1db96a4697791f0202cc8713f15640fd5,a0ab66394e3b9b542c18aff3dd97fdd8bbd4f607,497173c809dfa5259eb48f46e4dbce2f412958cc,CWE-611,1,CVE-2025-52888,2,2,True,False,False,False,False,False,False,False,False,False
8,False,GHSA-h7qf-qmf3-85qg,allure-framework/allure2,[CVE-2025-52888],### Summary\nA critical XML External Entity (XXE) vulnerability exists in the xunit-xml-plugin used by Allure 2. The plugin fails to securely configure the XML parser (`Documen...,Allure Report allows Improper XXE Restriction via DocumentBuilderFactory,[CWE-611],eaa87ff7d93e79074f7a1d785740bd3fed2f89fd,cbcb33719851ff70adce85d38e15d20fc58d4eb7,"[{'vuln_snippet': 'public class JunitXmlPlugin { private void parseRootElement(final Path resultsDirectory, final Path parsedFile, final ...","[{'vuln_context': '/** * Plugin that reads data in JUnit.xml format. * * @since 2.0 */ @SuppressWarnings({""PMD.ExcessiveImports"", ""ClassDataAbstractionCoupling"", ""ClassFanO...",GHSA-g6wm-2v64-wq36,0.85,0.95,Both vulnerabilities are XXE issues (CWE-611) with identical root causes: improper XML parser configuration allowing external entity resolution. Attack vectors differ slightly ...,Robothy/local-s3,d6ed756ceb30c1eb9d4263321ac683d734f8836f,009901882be8b543e85b67c5ec2e9f30d83d62ef,0244e9bbb5b1a9b6f8fa3f9c19fc9a9243f4fc97,CWE-611,1,CVE-2025-52888,2,2,True,False,False,False,False,False,False,False,False,False
56,True,GHSA-68j8-fp38-p48q,gematik/app-referencevalidator,[CVE-2024-46984],### Impact\nThe profile location routine in the referencevalidator commons package is vulnerable to [XML External Entities](https://owasp.org/www-project-top-ten/2017/A4_2017-X...,Gematik Referenzvalidator has an XXE vulnerability that can lead to a Server Side Request Forgery attack,[CWE-611],d276b02be9c836b3ccc6979df799e7dca06474ac,d6d27613fab7a8dd08534946f29e0c51f319cad6,[{'vuln_snippet': 'public class ReferencedProfileLocator { private List<String> locateInXml(String resource) throws IllegalArgumentException { XMLEventReader xmlEv...,[{'vuln_context': '@Slf4j public class ReferencedProfileLocator { private static final WstxInputFactory inputFactory = new WstxInputFactory(); private static final Jso...,GHSA-g6wm-2v64-wq36,0.92,0.95,Both vulnerabilities are XXE issues (CWE-611) with identical root causes: insecure XML parser configurations allowing external entity resolution leading to SSRF. Attack vectors...,Robothy/local-s3,d6ed756ceb30c1eb9d4263321ac683d734f8836f,009901882be8b543e85b67c5ec2e9f30d83d62ef,0244e9bbb5b1a9b6f8fa3f9c19fc9a9243f4fc97,CWE-611,1,CVE-2024-46984,1,1,True,False,False,False,False,False,False,False,False,False
57,True,GHSA-68j8-fp38-p48q,gematik/app-referencevalidator,[CVE-2024-46984],### Impact\nThe profile location routine in the referencevalidator commons package is vulnerable to [XML External Entities](https://owasp.org/www-project-top-ten/2017/A4_2017-X...,Gematik Referenzvalidator has an XXE vulnerability that can lead to a Server Side Request Forgery attack,[CWE-611],d276b02be9c836b3ccc6979df799e7dca06474ac,d6d27613fab7a8dd08534946f29e0c51f319cad6,[{'vuln_snippet': 'public class ReferencedProfileLocator { private List<String> locateInXml(String resource) throws IllegalArgumentException { XMLEventReader xmlEv...,[{'vuln_context': '@Slf4j public class ReferencedProfileLocator { private static final WstxInputFactory inputFactory = new WstxInputFactory(); private static final Jso...,GHSA-47qw-ccjm-9c2c,0.85,0.95,Both vulnerabilities are XXE (CWE-611) with identical root causes: insecure XML parser configurations allow external entity processing. Attack vectors differ slightly (multipar...,Robothy/local-s3,d6ed756ceb30c1eb9d4263321ac683d734f8836f,009901882be8b543e85b67c5ec2e9f30d83d62ef,0244e9bbb5b1a9b6f8fa3f9c19fc9a9243f4fc97,CWE-611,1,CVE-2024-46984,1,1,True,False,False,False,False,False,False,False,False,False
58,False,GHSA-68j8-fp38-p48q,gematik/app-referencevalidator,[CVE-2024-46984],### Impact\nThe profile location routine in the referencevalidator commons package is vulnerable to [XML External Entities](https://owasp.org/www-project-top-ten/2017/A4_2017-X...,Gematik Referenzvalidator has an XXE vulnerability that can lead to a Server Side Request Forgery attack,[CWE-611],d276b02be9c836b3ccc6979df799e7dca06474ac,d6d27613fab7a8dd08534946f29e0c51f319cad6,[{'vuln_snippet': 'public class ReferencedProfileLocator { private List<String> locateInXml(String resource) throws IllegalArgumentException { XMLEventReader xmlEv...,[{'vuln_context': '@Slf4j public class ReferencedProfileLocator { private static final WstxInputFactory inputFactory = new WstxInputFactory(); private static final Jso...,GHSA-6fhj-vr9j-g45r,0.85,0.95,Both vulnerabilities are XXE issues (CWE-611) caused by insecure XML parser configurations. They occur in different libraries and contexts (profile validation vs BOM validation...,CycloneDX/cyclonedx-core-java,af0ec75c93c03f93733a070c5132554490af5314,7c7294b3d112ba423c94b1f42994e6fb00fb241e,681ed28386b2135c5ff4ed9a3c895fa9c4900289,CWE-611,1,CVE-2024-46984,1,1,True,False,False,False,False,False,False,False,False,False
59,False,GHSA-68j8-fp38-p48q,gematik/app-referencevalidator,[CVE-2024-46984],### Impact\nThe profile location routine in the referencevalidator commons package is vulnerable to [XML External Entities](https://owasp.org/www-project-top-ten/2017/A4_2017-X...,Gematik Referenzvalidator has an XXE vulnerability that can lead to a Server Side Request Forgery attack,[CWE-611],d276b02be9c836b3ccc6979df799e7dca06474ac,d6d27613fab7a8dd08534946f29e0c51f319cad6,[{'vuln_snippet': 'public class ReferencedProfileLocator { private List<String> locateInXml(String resource) throws IllegalArgumentException { XMLEventReader xmlEv...,[{'vuln_context': '@Slf4j public class ReferencedProfileLocator { private static final WstxInputFactory inputFactory = new WstxInputFactory(); private static final Jso...,GHSA-8c3x-hq82-gjcm,0.85,0.95,Both vulnerabilities are XXE (CWE-611) with identical root cause: insecure XML parsing without disabling external entities. Attack vectors differ slightly (input stream vs file...,HL7/fhir-ig-publisher,3560de2f486d688a3ddcf4aa54d8bdacea380c3d,ba0b48d4ddb4dbffb45e0d45c43069e99a038385,ff300219c66c19d76fb5e08c92a4d487b71cf15c,CWE-611,1,CVE-2024-46984,1,1,True,False,False,False,False,False,False,False,False,False
60,False,GHSA-68j8-fp38-p48q,gematik/app-referencevalidator,[CVE-2024-46984],### Impact\nThe profile location routine in the referencevalidator commons package is vulnerable to [XML External Entities](https://owasp.org/www-project-top-ten/2017/A4_2017-X...,Gematik Referenzvalidator has an XXE vulnerability that can lead to a Server Side Request Forgery attack,[CWE-611],d276b02be9c836b3ccc6979df799e7dca06474ac,d6d27613fab7a8dd08534946f29e0c51f319cad6,[{'vuln_snippet': 'public class ReferencedProfileLocator { private List<String> locateInXml(String resource) throws IllegalArgumentException { XMLEventReader xmlEv...,[{'vuln_context': '@Slf4j public class ReferencedProfileLocator { private static final WstxInputFactory inputFactory = new WstxInputFactory(); private static final Jso...,GHSA-fvfq-q238-j7j3,0.85,0.95,Both vulnerabilities are XXE (CWE-611) caused by improper XML parser configuration allowing external entity resolution. Attack vector is similar: parsing untrusted XML input. C...,wso2/carbon-mediation,b995b2f1db96a4697791f0202cc8713f15640fd5,a0ab66394e3b9b542c18aff3dd97fdd8bbd4f607,497173c809dfa5259eb48f46e4dbce2f412958cc,CWE-611,1,CVE-2024-46984,1,1,True,False,False,False,False,False,False,False,False,False
61,False,GHSA-68j8-fp38-p48q,gematik/app-referencevalidator,[CVE-2024-46984],### Impact\nThe profile location routine in the referencevalidator commons package is vulnerable to [XML External Entities](https://owasp.org/www-project-top-ten/2017/A4_2017-X...,Gematik Referenzvalidator has an XXE vulnerability that can lead to a Server Side Request Forgery attack,[CWE-611],d276b02be9c836b3ccc6979df799e7dca06474ac,d6d27613fab7a8dd08534946f29e0c51f319cad6,[{'vuln_snippet': 'public class ReferencedProfileLocator { private List<String> locateInXml(String resource) throws IllegalArgumentException { XMLEventReader xmlEv...,[{'vuln_context': '@Slf4j public class ReferencedProfileLocator { private static final WstxInputFactory inputFactory = new WstxInputFactory(); private static final Jso...,GHSA-h7qf-qmf3-85qg,0.85,0.95,"Both vulnerabilities are XXE issues (CWE-611) caused by improper XML parser configuration, leading to SSRF. Different parsers used (Woodstox vs DocumentBuilderFactory), but sam...",allure-framework/allure2,cbcb33719851ff70adce85d38e15d20fc58d4eb7,eaa87ff7d93e79074f7a1d785740bd3fed2f89fd,28a7c494d73271824fff10bd5399bc976c0cc3b4,CWE-611,1,CVE-2024-46984,1,1,True,False,False,False,False,False,False,False,False,False
62,True,GHSA-68j8-fp38-p48q,gematik/app-referencevalidator,[CVE-2024-46984],### Impact\nThe profile location routine in the referencevalidator commons package is vulnerable to [XML External Entities](https://owasp.org/www-project-top-ten/2017/A4_2017-X...,Gematik Referenzvalidator has an XXE vulnerability that can lead to a Server Side Request Forgery attack,[CWE-611],d276b02be9c836b3ccc6979df799e7dca06474ac,d6d27613fab7a8dd08534946f29e0c51f319cad6,[{'vuln_snippet': 'public class ReferencedProfileLocator { private List<String> locateInXml(String resource) throws IllegalArgumentException { XMLEventReader xmlEv...,[{'vuln_context': '@Slf4j public class ReferencedProfileLocator { private static final WstxInputFactory inputFactory = new WstxInputFactory(); private static final Jso...,GHSA-jqfv-jrvq-95jm,0.85,0.95,"Both vulnerabilities are XXE issues (CWE-611) caused by improper restriction of XML external entities. They occur in Java-based XML processing contexts, though using different ...",apache/xmlgraphics-fop,d96ba9a11710d02716b6f4f6107ebfa9ccec7134,cb26fed42b675c576d8f4b69827a32a25e36c5bb,32c8c7176bf809ceff87398ba25a81760bbb9bb3,CWE-611,1,CVE-2024-46984,1,1,True,False,False,False,False,False,False,False,False,False

In [18]:
525/5

105.0